---
- name: deploy java application
  get_url:
    url: http://35.163.209.53:8081/artifactory/ttt/{{mybuild}}/target/mahaLogin-1.0.war
    dest: /opt/tomcat/webapps/mahaLogin.war
    username: admin
    password: password
    force_basic_auth: yes
