---
- hosts: 172.31.90.85
  become: yes
  tasks: 
  - name: execute linux command
    command: hostname -f 
    register: myresult
  - name: display the above task result
    debug:
      msg: "{{myresult}}"

