---
- hosts: 172.31.90.85
  become: yes
  tasks:
  - name: install git
    apt:
      name: git
      state: present
    tags: 1st

  - name: install wget
    apt:
      name: wget
      state: present
    tags: 2nd

  - name: install tree
    apt:
      name: tree
      state: present
    tags: 3rd


# i want to execute first task only 