---
- hosts: webservers
  become: yes
  tasks:
  - name: install webserver on ubuntu16
    apt:
     name: "{{webserversOnubuntu}}"
     state: present
    when: ansible_os_family =="Debian"
  - name: start webserver on ubuntu16
    service:
     name: "{{webserversOnubuntu}}"
     state: started
    when: ansible_os_family =="Debian"


  - name: install webserver on Redhat8
    yum:
     name: "{{webserversonRedhat}}"
     state: present
    when: ansible_os_family =="RedHat"
  - name: start webserver on Redhat8
    service:
     name: "{{webserversonRedhat}}"
     state: started
    when: ansible_os_family =="RedHat"