---
- hosts: win
  tasks:
  - name: ping all win hosts
    win_ping:
  - name: Install git
    win_chocolatey:
     name: git
     state: present
  - name: Install firefox
    win_chocolatey:
     name: Firefox
     state: present
  - name: Install notepad
    win_chocolatey:
     name: Notepadplusplus
     state: present